#!/usr/bin/env bash

# colors

RED="\e[31m"
GREEN="\e[32m"
YELLOW="\e[33m"
BLUE="\e[34m"
MAGENTA="\e[35m"
CYAN="\e[36m"
RESET="\e[0m"

ln -sf /usr/share/zoneinfo/Africa/Cairo /etc/localtime
hwclock --systohc

xbps-install -y fzf

#---------------------------------------------------------------------------------------------------

# configre disk

wait_for_choice() {
  read -n 1 key
  echo
  if [[ $key == "$choice1" ]]; then
    eval $option1
  elif [[ $key == "$choice2" ]]; then
    eval $option2
  fi
}

echo -e "${BLUE}    Do you ready for configrate the disk click (y) yes (n) no${RESET}"
choice1="y"
option1='cfdisk'
choice2="n"
option2='echo "retry when you are ready "'

wait_for_choice

#---------------------------------------------------------------------------------------------------

# mkdir

mkdir -p /mnt
mkdir -p /mnt/home
mkdir -p /mnt/var

#---------------------------------------------------------------------------------------------------

# mount point

echo "choose the disk"
disk=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -vE 'loop|zram' | fzf --prompt="Select a service: " --height=20% | awk '{print $1}')

echo "${BLUE}chose the root partetion ${RESET}"
root=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -vE 'loop|zram' | fzf --prompt="Select a service: " --height=20% | awk '{print $1}')
sudo mount /dev/$root /mnt

echo "${BLUE}chose the home partetion ${RESET}"
home=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -vE 'loop|zram' | fzf --prompt="Select a service: " --height=20% | awk '{print $1}')
sudo mount /dev/$home /mnt/home

echo "${BLUE}chose the var partetion ${RESET}"
var=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -vE 'loop|zram' | fzf --prompt="Select a service: " --height=20% | awk '{print $1}')
sudo mount /dev/$var /mnt/var

echo "${BLUE}chose the swap partetion ${RESET}"
swap=$(lsblk -o NAME,SIZE,TYPE,MOUNTPOINT | grep -vE 'loop|zram' | fzf --prompt="Select a service: " --height=20% | awk '{print $1}')
mkswap /dev/$swap
swapon /dev/$swap

#---------------------------------------------------------------------------------------------------

# xbps-keys

mkdir -p /mnt/var/db/xbps/keys/
sudo cp /var/db/xbps/keys/* /mnt/var/db/xbps/keys/

cat <<EOF >/etc/resolv.conf
# Generated by dhcpcd from enp0s29u1u2.dhcp
# /etc/resolv.conf.head can replace this line
#nameserver 192.168.129.75
nameserver 8.8.8.8
nameserver 1.1.1.1
#nameserver 192.168.1.2





# /etc/resolv.conf.tail can replace this line" 
EOF

xbps-install -Sy -R https://repo-default.voidlinux.org/current -r /mnt base-system

#---------------------------------------------------------------------------------------------------

# Get UUIDs
uuid_root=$(blkid -s UUID -o value /dev/$root)
uuid_home=$(blkid -s UUID -o value /dev/$home)
uuid_var=$(blkid -s UUID -o value /dev/$var)
uuid_swap=$(blkid -s UUID -o value /dev/$swap)

fs_root=$(blkid -o value -s TYPE /dev/$root)
fs_home=$(blkid -o value -s TYPE /dev/$home)
fs_var=$(blkid -o value -s TYPE /dev/$var)

#---------------------------------------------------------------------------------------------------

cat <<EOM >/mnt/install_inside.sh
#!/bin/env bash

# variables

disk="$1"
uuid_root="$2"
uuid_home="$3"
uuid_var="$4"
uuid_swap="$5"
fs_root="$6"
fs_home="$7"
fs_var="$8"

#---------------------------------------------------------------------------------------------------

echo "Choose password for root"

passwd

read -rp "write your username :\n" username
useradd -m -G wheel -s /bin/bash "$username"

echo "Choose password for your user"
passwd $username

xbps-reconfigure -fa


cat <<EON >/etc/fstab
#
# See fstab(5).
#
# <file system>                    	<dir>  	<type>	<options>	                     <dump>	<pass>
UUID=$uuid_root    /      $fs_root    defaults  0  1 
UUID=$uuid_home    /home  $fs_home    defaults  0  2
UUID=$uuid_var     /var   $fs_var     defaults  0  2
UUID=$uuid_swap    none   swap    sw        0  0

tmpfs		/tmp	tmpfs	defaults,nosuid,nodev   0       0 
EON

######################################################################################################

cat <<EOT >/etc/hostname
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>		<hostname.domain.org>	<hostname>
127.0.0.1		mz.mz	mz
::1			mz.mz	mz ip6-localhost

# End of file"
EOT

######################################################################################################

echo "mz" >>/etc/hosts

######################################################################################################

ln -sf /usr/share/zoneinfo/UTC /etc/localtime

xbps-install -y grub

if [ -d /sys/firmware/efi ]; then
    xbps-install -y grub-x86_64-efi efibootmgr
    mkdir -p /boot/efi
    mount /dev/$(lsblk -o NAME,TYPE | grep part | fzf --prompt="Select EFI partition: " | awk '{print $1}') /boot/efi
    grub-install --target=x86_64-efi --efi-directory=/boot/efi
else
    xbps-install -y grub
    grub-install /dev/"$disk"
fi

update-grub

exit
EOM

#---------------------------------------------------------------------------------------------------

# chroot

mount -t proc proc /mnt/proc
mount -t sysfs sys /mnt/sys
mount -o bind /dev /mnt/dev
mount -t devpts devpts /mnt/dev/pts
chroot /mnt /bin/bash /install_inside.sh "$disk" "$uuid_root" "$uuid_home" "$uuid_var" "$uuid_swap" "$fs_root" "$fs_home" "$fs_var"

umount -R /mnt

reboot
