#!/usr/bin/env bash

# ----------------------------
# Reset zram device if exists
# ----------------------------
if [ -b /dev/zram0 ]; then
    swapoff /dev/zram0 2>/dev/null
    echo 1 > /sys/block/zram0/reset
fi

# ----------------------------
# Load zram kernel module
# ----------------------------
modprobe zram

# ----------------------------
# Set compression algorithm
# ----------------------------
echo lz4 > /sys/block/zram0/comp_algorithm

# ----------------------------
# Set disksize (2G for your device)
# ----------------------------
echo 3G > /sys/block/zram0/disksize

# ----------------------------
# Initialize swap
# ----------------------------
mkswap /dev/zram0
swapon /dev/zram0

# ----------------------------
# Keep service alive
# ----------------------------
exec sleep infinity
