[greeter]
icon-theme-name = Adwaita++-Dark-Colorful
default-user-image = /home/mz/Pictures/my.png
background = /home/mz/Pictures/backgrounds/jonatan-pie-h8nxGssjQXs-unsplash.jpg
xft-antialias = false
theme-name = Adwaita-dark
position = 8%,start 50%,center
clock-format = %A, %H:%M %p

[monitor: LVDS-1]
background = /home/mz/Pictures/1.jpg
user-background = true

