;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
##background = #282A2E
##background-alt = #373B41
#background = #aa09090d
background =  #00000000  ; شفافية كاملة
#foreground = #ffffffff
foreground = #8897F4
##foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880
light-red = #D95B5B
light-green = #249824
light-purple = #A44BA0
menucol-yellow = #F7F272
menucol-blue = #1771F1
menucol-orange = #FFAF60
menucol-red = #F85C50
menucol-green = #77BD8B
menucol-sealine = #00CF91
menucol-purple = #9A76B3
menucol-pink = #FF77BF
menucol-deepblue = #6560FF
menucol-lightblue = #60FFF7
fav-purple = #6633FF
dark = #111
dark-red = #311
dark-green = #131
dark-purple = #201134
light = #eee
gray = #999
dark-gray = #333
uo_linecolor = #7E57C0
border-color = #00000000


[bar/i3]
width = 100%
height = 14pt   
radius = 8
#

#bottom = true
fixed-center = true
#offset-x =0%
#offset-y =0%
border-size =  4pt
border-color = #00000000
#radius = 8
radius-top =  8
radius-bottom = 8
line-size = 3pt
line-color = ${color.background}

; dpi = 8

background = ${colors.background}
foreground = ${colors.foreground}


margin-top = 0
margin-bottom = 0
margin-left = 0
margin-right = 0


padding-left = 1
padding-right = 1
odule-margin = 1

separator = |
separator-foreground = ${colors.disabled}

#font 
font-0 = "Noto Sans Symbols:size=12;2"
font-1 = "Font Awesome 6 Free:style=Solid:pixelsize=12"
font-2 = "Hack:style=Regular:pixelsize=12;2"
font-3 = "Iosevka Nerd Font:size=10;4"
font-4 = "Iosevka Nerd Font:size=10;3"
font-5 = "feather:size=12;3"
font-6 = "Iosevka Nerd Font:size=12;4"
font-7 = "OpenSymbol :size=12;4"
font-8 = "NanumBarunGothic :size=12;4"
font-9 = "Unifont CSUR :size=12;4"
font-10 ="Noto Sans Arabic,Noto Sans Arabic Cond :size=12;4"
font-11 =" Noto Sans Arabic:style=Regular:size=11"
font-12 = "JetBrainsMono Nerd Font:size=10;1"  
font-13 = "Noto Color Emoji:size=10;1" 


#modules
modules-left = xworkspaces powermenu memoryswap  
modules-right = brightness pulseaudio xkeyboard memory cpu time
modules-center = 

#cursor-click = pointer
#cursor-scroll = ns-resize
enable-ipc = true
tray-position = center
tray-detached = false
tray-maxsize = 16
tray-background = ${color.background}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 5
tray-scale = 1

#wm-restack = dwm 
#override-redirect = true

cursor-click = pointer
#cursor-scroll = ns-resize

click-left =
click-middle =
click-right =
double-click-left =
double-click-middle =
double-click-right =
scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev
#scroll-up = i3-msg workspace next_on_output
#scroll-down = i3-msg workspace prev_on_output

[module/dwm]
type = custom/script
exec = dwm-polybar --padding 1 --active-bg #7e9cd8 --urgent-bg #c34043
tail = true

[module/tri-upper-right]
type = custom/text

content = %{T2} %{T-}
content-foreground = #151515

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = true
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = true

; --- وحدات التحكم في VLC ---

[module/pipewire]
type = internal/pipewire

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}


[module/vlc-prev]
type = custom/script
exec = echo "  " 
click-left = playerctl previous -p vlc
format = <label>

[module/vlc-play]
type = custom/script
; أيقونة التشغيل (من Nerd Fonts)
exec = echo ""
click-left = playerctl play -p vlc
scroll-up = playerctl --player=vlc volume 0.05+
scroll-down = playerctl --player=vlc volume 0.05-
format = <label>

[module/vlc-pause]
type = custom/script
; أيقونة الإيقاف المؤقت (من Nerd Fonts)
exec = echo ""
click-left = playerctl pause -p vlc
scroll-up = playerctl --player=vlc volume 0.05+
scroll-down = playerctl --player=vlc volume 0.05-
format = <label>

[module/vlc-next]
type = custom/script
exec = echo "  " 
click-left = playerctl next -p vlc
format = <label>

; --- نهاية وحدات التحكم في VLC ---

[module/mpd]
type = internal/mpd
host = 127.0.0.1
port = 6600
format-online = <icon-prev> <toggle> <icon-next> %{A1:~/.config/rofi/scripts/mpd.sh:}<label-song>%{A}%{A1:bspc desktop -f V:}<label-time>%{A}
format-online-padding = 2 
format-online-foreground = ${colors.foreground}
format-online-background = ${colors.background}
label-song-foreground = ${colors.foreground}
label-song-background = ${colors.background}
label-song-padding = 2
label-time-foreground = ${colors.foreground}
label-time-background = ${colors.background}
label-time-padding = 1
format-online-overline = ${colors.uo_linecolor}

format-offline = <label-offline>
label-offline =
; offline
format-offline-padding = 2
format-offline-foreground = ${colors.foreground}
format-offline-background = ${colors.background}

bar-progress-width = 35
bar-progress-indicator = |
bar-progress-fill = ─
bar-progress-empty = ─



icon-prev = 
icon-stop = 
icon-play = 
iicon-pause = 
con-next = 

label-song-maxlen = 75
label-song-ellipsis = true

[module/kbstates]
type = custom/script
format = <label>
format-underline = ${colors.menucol-green}
format-padding = 0
format-underline-font = 0.1
format-foreground = #8897F4
exec = $HOME/.config/polybar/kblocks.py
interval = 0.5
label-font = 12
label-foreground = ${colors.menucol-green}

[module/time]
type = internal/date
date =%I:%M:%S %p 
date-alt =%A, %d %B %Y
date-foreground = #8897F4
date-aٌٌٌٌٌٌٌٌlt-foreground = #8897F4

[module/power]
type = custom/script
exec = echo "#"
click-left = ~/.config/rofi/menue-power.sh
label = %output%
labelforeground = #8897F4

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/brightness]
type = custom/script
exec = ~/.config/polybar/brightness.sh
interval = 5
click-left = brightnessctl set 5%-
click-right = brightnessctl set +5%
scroll-up = brightnessctl set +1%
scroll-down = brightnessctl set 1%-


[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock
format-prefix-foreground = ${colors.primary}
format = <label-layout>
label-layout = %layout%
label-layout-padding = 2


[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}



[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/memoryswap]
type = internal/memory
interval = 3
format = <label>
format-padding = 2
format-underline = ${colors.menucol-pink}
format-prefix =       
format-prefix-foreground = ${colors.menucol-pink}
label = %gb_swap_used%
label-font = 3

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%
[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/alsa]
type = internal/alsa

; Soundcard to be used
; Usually in the format hw:# where # is the card number
; You can find the different card numbers in `/proc/asound/cards`
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

; Name of the master, speaker and headphone mixers
; Use the following command to list available mixer controls:
; $ amixer scontrols | sed -nr "s/.*'([[:alnum:]]+)'.*/\1/p"
; If master, speaker or headphone-soundcard isn't the default,
; use `amixer -c # scontrols` instead where # is the number
; of the master, speaker or headphone soundcard respectively
;
; Default: Master
master-mixer = Master

; Optionally define speaker and headphone mixers
; Default: none
;;speaker-mixer = Speaker
; Default: none
;;headphone-mixer = Headphone

; NOTE: This is required if headphone_mixer is defined
; Use the following command to list available device controls
; $ amixer controls | sed -r "/CARD/\!d; s/.*=([0-9]+).*name='([^']+)'.*/printf '%3.0f: %s\n' '\1' '\2'/e" | sort
; You may also need to use `amixer -c # controls` as above for the mixer names
; Default: none
;;headphone-id = 9

; Use volume mapping (similar to amixer -M and alsamixer), where the increase in volume is linear to the ear
; Default: false
;;mapped = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume> <label-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>
format-muted-prefix = 
format-muted-prefix-foreground = ${color.red}

; Available tokens:
;   %percentage% (default)
label-volume = %percentage%%

; Available tokens:
;   %percentage% (default
label-muted = " Muted"
label-muted-foreground = ${color.sep}

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${color.blue}

; If defined, it will replace <ramp-volume> when
; headphones are plugged in to `headphone_control_numid`
; If undefined, <ramp-volume> will be used for both
; Only applies if <ramp-volume> is used
ramp-headphones-0 = 
ramp-headphones-background = ${color.blue}

[module/powermenu]
type = custom/menu

expand-right = true

format-spacing = 1

label-open =#  
label-open-foreground = ${colors.secondary}
label-close =  cancel
label-close-foreground = ${colors.secondary}
label-separator = |
label-separator-foreground = ${colors.foreground-alt}


# Main menu
menu-0-0 = reboot
menu-0-0-exec = menu-open-1

menu-0-1 = poweroff
menu-0-1-exec = menu-open-2

menu-0-2 = susbend
menu-0-2-exec = sleep 

menu-0-3 = hibernate
menu-0-3-exec = zzz -Z

menu-0-4 = logout
menu-0-4-exec = i3-msg exit

# Submenu for reboot
menu-1-0 = reboot
menu-1-0-exec = reboot -n

menu-1-1 = exet
menu-1-1-exec = menu-open-0

# Submenu for poweroff
menu-2-0 = poweroff
menu-2-0-exec = poweroff -n

menu-2-1 = exet
menu-2-1-exec = menu-open-0

[module/round-left]
type = custom/text
content = %{T6}%{T-}
content-foreground = ${colors.bg}

[module/round-right]
type = custom/text
content = %{T6}%{T-}
content-foreground = ${colors.bg}

; vim:ft=dosini
